---
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    bucket_name: '{{ lookup("env", "BUCKET_NAME") }}'
  tasks:
    - name: create updated bucket policy file
      shell: sed "s/bucket_name/{{bucket_name}}/g" policy.json > policy2.json
    - amazon.aws.s3_bucket:
        name: "{{bucket_name}}"
        state: present
        policy: "{{ lookup('file','policy2.json') }}"
    - community.aws.s3_website:
        name: "{{bucket_name}}"
        state: present
    - s3_sync:
        bucket: "{{bucket_name}}"
        file_root: dist/
    - name: cleanup policy file
      shell: rm policy2.json